Plural/Controllers/AppController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Plural.Data;
using Plural.Services;
using Plural.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Plural.Controllers
{
    public class AppController : Controller
    {
        // INJECT THE SERVICE
        private readonly IMailService _mailService;
        private readonly IPluralRepository _repository;

        public AppController(IMailService mailService, IPluralRepository repository)
        {
            _mailService = mailService;
            _repository = repository;
        }

        [Authorize]
        public IActionResult Shop()
        {
            return View();
        }
        
        public IActionResult Index()
        {

            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            ViewBag.Title = "Contact Us";

            return View();
        }
        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                _mailService.SendMessage("vsi1@abv.bg", "SUBJECT", $"From: {model.Email}, Message: {model.Message}");
                ViewBag.UserMessage = "Mail send";
                // CLEAR THE FORM
                ModelState.Clear();
            } 
           
            return View();
        }
        [HttpGet("about")]
        public IActionResult About()
        {
            ViewBag.Title = "About";

            return View();
        }
    }
    
}

Plural/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />


    <link href="~/lib/font-awesome/web-fonts-with-css/css/fontawesome-all.min.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
    <h1>@ViewBag.Title</h1>
    <ul>
        <li><a asp-controller="App" asp-action="About">About</a></li>
        <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        @if (User.Identity.IsAuthenticated)
        {
            <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
        }
        else
        {
            <li><a asp-controller="Account" asp-action="Login">Login</a></li>

        }
    </ul>
    @RenderBody()
    <script src="~/lib/jQuery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts", false) <!--FALSE NOT REQUIRED NOT EVERY PAGE-->
</body>
</html>